Consolidate Visual C++ and GCC subprojects and set up CI
EmpowerOperations/volition pull request #36
Opened 2023-11-11 19:30 UTC by vchlin

- Consolidate Visual C++ and GCC subprojects
- Expand CMake presets to add support for Linux
- Documentation update
- Add a GitHub action file to set up CI

2023-11-16 23:28 UTC, Groostav requested changes
This looks good vincent

Before i approve it I'm going to ask cenk to check it out and build it on his machine.

If he cant I'll come back and issue an approval and assume that the github actions success is sufficient. 

Along those lines, how is github actions when it fails? Does it give you useful logs for debugging? If you introduce a compiler error and push it, does github actions take the compilation errors and forward them to a failure report screen?

Anyways, only a few things i've asked you to do here. Give me some comments and hopefuly before you do ill get back to you regarding approval

2023-11-16 23:28 UTC, Groostav commented on gcc-client-reference/optimizer.pb.h
Regarding generated code deletion: I think this is fine so long as people can easily run cmake. Our previous partners have simply copy-pasted this code into their environment to run it --they may have had to comment out some `#ERROR` stateements because they couldnt get exactly the same version, which is bad for the reasons you mentioned in the previous PR.

I would like to run this before approving it, but i am always glad to get generated code out of the repo.

2023-11-18 21:55 UTC, vchlin commented on .github/workflows/cmake-multi-platform.yml
> +    branches: [ "master" ]
It means GitHub actions run when the `master` branch is pushed or when pull requests against `master` are created (or updated). I can enable them for all branches if we think that's necessary.

2023-11-18 21:59 UTC, vchlin commented on .github/workflows/cmake-multi-platform.yml
> +    runs-on: ${{ matrix.os }}
It's how GitHub actions handle multi-platform testing. This expands into the combinations of platforms / configs you specify.

2023-11-18 22:08 UTC, vchlin commented on .github/workflows/cmake-multi-platform.yml
> +            preset: x64-linux-clang-release
Yeah one run each. A preset here is a compiler toolchain plus a set of features, flags, env etc. to use when building the project. This is entirely user-defined and  is just one dimension of the matrix. `os` is a built-in provided by the build matrix though.

2023-11-18 22:10 UTC, vchlin commented on cpp-client-reference/CMakePresets.json
> +        "CMAKE_CXX_COMPILER": "cl.exe"
Yeah, this is just MSVC.

2023-11-18 22:13 UTC, vchlin commented on cpp-client-reference/CMakePresets.json
> +      "hidden": true,
Yeah. This is just an "abstract" config that other configs inherit from. When it's hidden, the user can't ask to use it directly.

2023-11-18 22:15 UTC, vchlin commented on cpp-client-reference/CMakePresets.json
> +        "rhs": "Linux"
Yeah. This is just CMake stuff and doesn't have to with GitHub.

2023-11-18 22:21 UTC, vchlin commented on cpp-client-reference/CMakePresets.json
> +}
This is by convention. I believe this is now the recommended way to supply multiple supported configs with CMake.

2023-11-18 22:25 UTC, vchlin commented on gcc-client-reference/optimizer.pb.h
Yeah valid concern. I am thinking we can provide them with a release containing generated files in that case. What do you think?

2023-11-18 22:40 UTC, vchlin commented
> This looks good vincent
> 
> Before i approve it I'm going to ask cenk to check it out and build it on his machine.
> 
> If he cant I'll come back and issue an approval and assume that the github actions success is sufficient.
> 
> Along those lines, how is github actions when it fails? Does it give you useful logs for debugging? If you introduce a compiler error and push it, does github actions take the compilation errors and forward them to a failure report screen?
> 
> Anyways, only a few things i've asked you to do here. Give me some comments and hopefuly before you do ill get back to you regarding approval

Thanks for looking, Geoff. So GitHub actions show everything that goes to stdout / stderr, which include all compilation errors. This is fine for our own code. One issue though is that Vcpkg likes to put its build errors in a log file and tells you to go look. But AFAICT there's no easy way to access this file. I'll probably add an action step that `cat`s the log when it fails.

2023-11-18 22:59 UTC, vchlin commented on .github/workflows/cmake-multi-platform.yml
> +        -B ${{ steps.strings.outputs.source-dir }}/out
Good point. Fixed. 

I think in practise this should be fine though. GitHub actions set up the workspace for us and I'd think they wouldn't make things difficult for people.

2023-11-18 22:59 UTC, vchlin commented on .github/workflows/cmake-multi-platform.yml
> +      run: cmake --build ${{ steps.strings.outputs.source-dir }}/out --config ${{ matrix.build_type }}
Fixed.

2023-11-23 21:09 UTC, cferidun commented
I am able to compile (VS2022) and run cpp reference client with OASIS Volition 2023.

2023-11-24 03:54 UTC, vchlin commented
> I am able to compile (VS2022) and run cpp reference client with OASIS Volition 2023.

Thanks for looking, Cenk! Can I go ahead and merge this?

2023-11-25 22:15 UTC, cferidun commented
Yes, you can. Thank you.

2023-11-25 23:44 UTC, merged